apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvpbackendapp
  labels:
    app: rsvpbackendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsvpbackendapp
  template:
    metadata:
      labels:
        app: rsvpbackendapp
    spec:
      containers:
        - name: rsvpbackendapp
          image: dockerrajmanda/rsvpbackend:23
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: restaurantdb_url
---
apiVersion: v1
kind: Service
metadata:
  name: rsvpbackendapp-service
spec:
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: rsvpbackendapp
 