apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvpbackend
  namespace: kalyanam
  labels:
    app: rsvpbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsvpbackend
  template:
    metadata:
      labels:
        app: rsvpbackend
    spec:
      serviceAccountName: gke-secret-accessor  # Use the Kubernetes Service Account
      volumes:
        - name: tmp-volume
          emptyDir: {}  # Create a writable empty directory
        - name: secret-volume
          emptyDir: {}  # Shared volume for the MongoDB password

      initContainers:
#        - name: fetch-mongodb-password
#          image: dockerrajmanda/rsvpbackend:10
        - name: gcloud-container
          image: dockerrajmanda/rsvpbackend:10

          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets  # Mount the secret-volume here too
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Checking GCP authentication..."
              gcloud auth list
              echo "Fetching MongoDB password from GCP Secret Manager..."
              mkdir -p /etc/secrets  # Create the directory explicitly
              gcloud secrets versions access latest --secret=galadb_password > /etc/secrets/mongodb_password
              echo "Password fetched successfully."

      containers:
        - name: rsvpbackend
          image: dockerrajmanda/rsvpbackend:10
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmpdir
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true  # Ensure it's read-only in the main container
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: MONGODB_PASSWORD_FILE
              value: /etc/secrets/mongodb_password  # Point to the file in the mounted volume
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false  # Corrected typo: 'fals' to 'false'
---
apiVersion: v1
kind: Service
metadata:
  name: rsvpbackend
  namespace: kalyanam
spec:
  selector:
    app: rsvpbackend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
  type: ClusterIP