logging:
  level:
    com.gala.celebrations.rsvpbackend: DEBUG

spring:
  application:
    name: rsvpbackend
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  data:
    mongodb:
      #uri: mongodb+srv://amirrajAdmin:<password>@cluster0.sod5j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      uri: mongodb+srv://galaDbUser:<password>@cluster0.sod5j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: galadb
      passwordFilePath: /etc/secrets/mongodb_password
      password: dummyPassword
  mail:
    host: smtp.gmail.com
    port: 587
    username: raj.manda@gmail.com
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    # This is the key for production-like profiles
    passwordFilePath: /etc/secrets/gmail_password
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers, heapdump, threaddump, scheduledtasks, beans, caches
  health:
    mongodb:
      enabled: true  # Enable MongoDB health check

gcs:
  bucket-name: shravani_kalyanam_bucket