logging:
  level:
    com.gala.celebrations.rsvpbackend: DEBUG

spring:
  application:
    name: rsvpbackend
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${MONGODB_DATABASE:galadb}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers, heapdump, threaddump, scheduledtasks, beans, caches
  health:
    mongodb:
      enabled: true

gcs:
  bucket-name: ${GCS_BUCKET_NAME:shravani_kalyanam_bucket}