logging:
  level:
    com.gala.celebrations.rsvpbackend: INFO


spring:

  servlet:
    multipart:
      max-file-size: 2500MB
      # Set the maximum size for a multi-file request (e.g., 50 Megabytes)
      max-request-size: 5GB

  application:
    name: rsvpbackend
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://galaDbUser:<password>@cluster0.sod5j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:galadb}
    mail:
      host: smtp.gmail.com
      port: 587
      password: ${SPRING_MAIL_PASSWORD:default-password-for-non-dev-or-placeholder}
      username: ${SPRING_MAIL_USERNAME:raj.manda@gmail.com}
      properties:
        mail:
          debug: true
          smtp:
            auth: true
            starttls:
              enable: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers, heapdump, threaddump, scheduledtasks, beans, caches
  health:
    mongodb:
      enabled: true

gcs:
  bucket-name: ${GCS_BUCKET_NAME:shravani_kalyanam_bucket}
  signer-sa-email: ${GCS_SIGNER_SA_EMAIL:gcp-secret-accessor@properties-app-418208.iam.gserviceaccount.com}