server:
  port: 8443

# Eureka is used for service discovery, allowing services to find and communicate with each other dynamically.
# Eureka is primarily designed for server-side service discovery
# Removing it as we don't need it and can save us some $$$

#eureka:
#  client:
#    service-url:
#      defaultZone: http://my-eureka-headless.eureka.svc.cluster.local:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    hostname: rsvpbackend
#    secure-port: 8443
#    secure-port-enabled: true
#    status-page-url: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/actuator/info
#    health-check-url: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/actuator/health

spring:
  data:
    mongodb:
      #uri: mongodb+srv://amirrajAdmin:<password>@cluster0.sod5j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      uri: mongodb+srv://galaDbUser:<password>@cluster0.sod5j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: galadb
      passwordFilePath: /path/to/mongo-password.txt
      password: dummyPassword

