#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
#    hostname: rsvpbackend
#    non-secure-port: 8080
#    status-page-url: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/actuator/info
#    health-check-url: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/actuator/health

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://galaDbUser:<password>@cluster0.sod5j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:raj.manda@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:vtulvlpefdkpqzvi}
    passwordFilePath: ${MAIL_PASSWORD_FILE:/etc/secrets/gmail_password}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

# Local development settings
# Development tools and debugging
  devtools:
    restart:
      enabled: true
  jmx:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /

# Actuator configuration for local development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
