#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
#    hostname: rsvpbackend
#    non-secure-port: 8080
#    status-page-url: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/actuator/info
#    health-check-url: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/actuator/health

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${MONGODB_DATABASE:galadb}
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

# Local development settings
server:
  port: 8080
  servlet:
    context-path: /

# Development tools and debugging
spring:
  devtools:
    restart:
      enabled: true
  jmx:
    enabled: true

# Actuator configuration for local development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
