server:
  port: 8080

eureka:
  client:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers, heapdump, threaddump, scheduledtasks, beans, caches
  health:
    mongodb:
      enabled: true  # Enable MongoDB health check